src/main/java/ortus/boxlang/runtime/bifs/global/string/ReEscape.java
src/test/java/ortus/boxlang/runtime/bifs/global/string/ReEscapeTest.java

Adding the BIF for ReEscape function

Add ReEscape BIF

---

src/main/java/ortus/boxlang/runtime/bifs/global/math/RandRange.java
src/main/java/ortus/boxlang/runtime/bifs/global/math/Randomize.java
src/main/java/ortus/boxlang/runtime/scopes/Key.java
src/test/java/ortus/boxlang/runtime/bifs/global/math/RandomizeTest.java

Added Randomize BIF for Rand seeding

Added Randomize BIF for Rand seeding

---

src/main/java/ortus/boxlang/runtime/bifs/global/math/PrecisionEvaluate.java
src/main/java/ortus/boxlang/runtime/scopes/Key.java
src/test/java/ortus/boxlang/runtime/bifs/global/math/PrecisionEvaluateTest.java

Added precisionEvaluate BIF and tests

Added precisionEvaluate BIF and tests

---

src/main/java/ortus/boxlang/runtime/bifs/global/conversion/ParseNumber.java
src/test/java/ortus/boxlang/runtime/bifs/global/conversion/ParseNumberTest.java
src/test/java/ortus/boxlang/runtime/bifs/global/system/GetSystemSettingTest.java

@jclausen Please review changes
parseNumber fixes
this works in Lucee `parseNumber(1010,"HEX")`

parsenumber fixes

---

src/main/java/ortus/boxlang/runtime/bifs/global/io/DirectoryList.java
src/main/java/ortus/boxlang/runtime/types/AbstractFunction.java
src/main/java/ortus/boxlang/runtime/types/Array.java
src/main/java/ortus/boxlang/runtime/types/Function.java
src/main/java/ortus/boxlang/runtime/types/NullValue.java
src/main/java/ortus/boxlang/runtime/types/QueryColumn.java
src/main/java/ortus/boxlang/runtime/util/EncryptionUtil.java

doc improvements and implemented switch expression

doc improvements

---

src/main/java/ortus/boxlang/runtime/dynamic/casters/BooleanCaster.java
src/test/java/ortus/boxlang/runtime/dynamic/casters/BooleanCasterTest.java

booleancaster complex object tests and improvements

booleancaster tests

---

src/main/java/ortus/boxlang/compiler/Boxpiler.java
src/main/java/ortus/boxlang/runtime/config/Configuration.java
src/main/java/ortus/boxlang/runtime/scopes/Key.java
src/test/java/TestCases/phase3/ClassTest.java

Initial implementation of trusted cache functionality
https://ortussolutions.atlassian.net/browse/BL-488

BL-488 - Initial Trusted Cache Implementation

---

build.gradle
changelog.md
gradle.properties
src/main/java/ortus/boxlang/runtime/BoxRunner.java

version bump

---

src/main/java/ortus/boxlang/runtime/operators/Divide.java
src/main/java/ortus/boxlang/runtime/operators/Minus.java
src/main/java/ortus/boxlang/runtime/operators/Multiply.java
src/test/java/ortus/boxlang/runtime/operators/DivideTest.java
src/test/java/ortus/boxlang/runtime/operators/MinusTest.java
src/test/java/ortus/boxlang/runtime/operators/MultiplyTest.java
src/test/java/ortus/boxlang/runtime/operators/PlusTest.java

Allows date math for multiplication, division and subtraction.
Resolves https://ortussolutions.atlassian.net/browse/BL-1501

BL-1501 Resolve - add support for date math with *,-, and /

---

src/main/java/ortus/boxlang/runtime/components/net/HTTP.java
src/main/java/ortus/boxlang/runtime/net/HttpRequestMultipartBody.java

https://ortussolutions.atlassian.net/browse/BL-1507

BL-1507 Resolve 

---

src/main/java/ortus/boxlang/runtime/bifs/global/zip/Compress.java
src/main/java/ortus/boxlang/runtime/components/zip/Zip.java
src/main/java/ortus/boxlang/runtime/scopes/Key.java
src/main/java/ortus/boxlang/runtime/util/ZipUtil.java
src/main/java/ortus/boxlang/runtime/validation/Validator.java
src/test/java/ortus/boxlang/runtime/util/ZipUtilTest.java

Add `compressionLevel` to the zip component and utilities

BL-1508 #resolve

---

src/main/java/ortus/boxlang/runtime/components/net/HTTP.java
src/main/java/ortus/boxlang/runtime/util/ZipUtil.java

https://ortussolutions.atlassian.net/browse/BL-1511

BL-1511 Resolve - Add support for HTTP Compression

---

src/main/java/ortus/boxlang/runtime/jdbc/QueryOptions.java
src/test/java/ortus/boxlang/runtime/bifs/global/jdbc/QueryExecuteTest.java

Per Luis, don't use a ZERO duration, just use a null.

Default cache timeouts to null

---

src/main/java/ortus/boxlang/runtime/cache/BoxCache.java
src/main/java/ortus/boxlang/runtime/cache/BoxCacheEntry.java
src/main/java/ortus/boxlang/runtime/cache/ICacheEntry.java
src/main/java/ortus/boxlang/runtime/cache/providers/AbstractCacheProvider.java
src/main/java/ortus/boxlang/runtime/cache/providers/BoxCacheProvider.java
src/main/java/ortus/boxlang/runtime/cache/providers/CoreProviderType.java
src/main/java/ortus/boxlang/runtime/cache/providers/ICacheProvider.java
src/main/java/ortus/boxlang/runtime/util/conversion/ObjectMarshaller.java
src/test/java/ortus/boxlang/runtime/cache/BoxCacheEntryTest.java
src/test/java/ortus/boxlang/runtime/cache/providers/BoxCacheProviderTest.java

Add lazy expiration for caching
BL-1529 #resolve
Several concurrency issues on cache entries created and last access timeouts
BL-1530 #resolve
cache entry equals evaluating the hash codes incorrectly and causing collisions

BL-1528 BL-1530

---

src/main/java/ortus/boxlang/runtime/bifs/global/array/ArrayNone.java
src/main/java/ortus/boxlang/runtime/bifs/global/list/ListEvery.java
src/main/java/ortus/boxlang/runtime/bifs/global/list/ListNone.java
src/main/java/ortus/boxlang/runtime/bifs/global/query/QueryEvery.java
src/main/java/ortus/boxlang/runtime/bifs/global/query/QueryNone.java
src/main/java/ortus/boxlang/runtime/bifs/global/struct/StructNone.java
src/test/java/ortus/boxlang/runtime/bifs/global/array/ArrayNoneTest.java
src/test/java/ortus/boxlang/runtime/bifs/global/list/ListNoneTest.java
src/test/java/ortus/boxlang/runtime/bifs/global/query/QueryNoneTest.java
src/test/java/ortus/boxlang/runtime/bifs/global/struct/StructNoneTest.java

xNone() for bif operations: array, list, query, struct

BL-1533 #resolve

---

src/main/java/ortus/boxlang/runtime/bifs/global/temporal/ParseDateTime.java
src/main/java/ortus/boxlang/runtime/dynamic/casters/DateTimeCaster.java
src/main/java/ortus/boxlang/runtime/types/DateTime.java
src/main/java/ortus/boxlang/runtime/util/LocalizationUtil.java
src/test/java/ortus/boxlang/runtime/bifs/global/temporal/ParseDateTimeTest.java
src/test/java/ortus/boxlang/runtime/bifs/global/temporal/TimeUnitsTest.java

All PRs must have an accompanied Jira issue. Please make sure you created it and linked it here.
https://ortussolutions.atlassian.net/browse/BL-1570
https://ortussolutions.atlassian.net/browse/BL-1571
-

BL-1570 and BL-1571

---

src/main/java/ortus/boxlang/runtime/BoxRuntime.java
src/main/java/ortus/boxlang/runtime/application/BaseApplicationListener.java
src/main/java/ortus/boxlang/runtime/components/system/Component.java
src/main/java/ortus/boxlang/runtime/config/Configuration.java
src/main/java/ortus/boxlang/runtime/context/RequestBoxContext.java
src/main/java/ortus/boxlang/runtime/loader/resolvers/BoxResolver.java
src/main/java/ortus/boxlang/runtime/scopes/Key.java
src/main/resources/config/boxlang.json
src/test/java/TestCases/components/BoxTemplateTest.java
src/test/java/TestCases/components/CFTemplateTest.java
src/test/java/ortus/boxlang/runtime/bifs/global/system/GetBaseTagDataTest.java
src/test/java/ortus/boxlang/runtime/bifs/global/system/GetBaseTagListTest.java
src/test/java/ortus/boxlang/runtime/components/system/AssociateTest.java
src/test/java/ortus/boxlang/runtime/components/system/ModuleTest.java

BL-1577
lookup of custom componets and classes refactoring for performance
BL-1576
Refactor customTagsDirectory to customComponentsDirectory and add shim to support it for cfml and backwards compat

BL-1577 and BL-1576

---

src/main/java/ortus/boxlang/runtime/async/BoxFuture.java
src/main/java/ortus/boxlang/runtime/bifs/global/async/AsyncAll.java
src/main/java/ortus/boxlang/runtime/bifs/global/async/AsyncAllApply.java
src/main/java/ortus/boxlang/runtime/bifs/global/async/AsyncAny.java
src/main/java/ortus/boxlang/runtime/interop/proxies/BaseProxy.java
src/main/java/ortus/boxlang/runtime/scopes/Key.java
src/main/java/ortus/boxlang/runtime/services/AsyncService.java
src/test/java/ortus/boxlang/runtime/bifs/global/async/AsyncAllApplyTest.java
src/test/java/ortus/boxlang/runtime/bifs/global/async/AsyncAllTest.java
src/test/java/ortus/boxlang/runtime/bifs/global/async/AsyncAnyTest.java

[BL-1609](https://ortussolutions.atlassian.net/browse/BL-1609)
asyncAll, asyncAllApply, asyncAny bifs and constructs for parallel programming
[BL-1415](https://ortussolutions.atlassian.net/browse/BL-1415)
Cast error on BoxFuture.all()
[BL-1609]: https://ortussolutions.atlassian.net/browse/BL-1609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BL-1415]: https://ortussolutions.atlassian.net/browse/BL-1415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

asyncAll, asyncAllApply, asyncAny bifs and constructs for parallel programming

---

src/main/java/ortus/boxlang/runtime/types/QueryColumn.java
src/test/java/ortus/boxlang/runtime/bifs/global/system/ObjectMarshallerTest.java

Remove transient keywords so QueryColumn object can be properly deserialized
https://ortussolutions.atlassian.net/browse/BL-1624

BL-1624 Resolve

---

src/main/java/ortus/boxlang/runtime/components/zip/Zip.java
src/main/java/ortus/boxlang/runtime/components/zip/ZipParam.java
src/main/java/ortus/boxlang/runtime/scopes/Key.java
src/main/java/ortus/boxlang/runtime/util/ZipUtil.java
src/test/java/ortus/boxlang/runtime/components/zip/ZipTest.java

BL-1515 Resolve, BL-1623 Resolve - initial implementation of ZipParam component
https://ortussolutions.atlassian.net/browse/BL-1515
https://ortussolutions.atlassian.net/browse/BL-1632

BL-1515 - Initial ZipParam Component Implementation

---

.github/workflows/tests.yml
build.gradle
src/main/java/ortus/boxlang/runtime/components/jdbc/DBInfo.java
src/main/java/ortus/boxlang/runtime/components/jdbc/StoredProc.java
src/main/java/ortus/boxlang/runtime/jdbc/ConnectionManager.java
src/main/java/ortus/boxlang/runtime/jdbc/DataSource.java
src/main/java/ortus/boxlang/runtime/jdbc/ExecutedQuery.java
src/main/java/ortus/boxlang/runtime/jdbc/PendingQuery.java
src/main/java/ortus/boxlang/runtime/modules/ModuleRecord.java
src/main/java/ortus/boxlang/runtime/scopes/Key.java
src/main/java/ortus/boxlang/runtime/types/Query.java
src/main/java/ortus/boxlang/runtime/types/exceptions/DatabaseException.java
src/test/java/ortus/boxlang/runtime/bifs/global/jdbc/BaseJDBCTest.java
src/test/java/ortus/boxlang/runtime/bifs/global/query/QueryGetResultTest.java
src/test/java/ortus/boxlang/runtime/jdbc/DataSourceTest.java
src/test/java/ortus/boxlang/runtime/jdbc/drivers/AbstractDriverTest.java
src/test/java/ortus/boxlang/runtime/jdbc/drivers/MSSQLDriverTest.java
src/test/java/ortus/boxlang/runtime/jdbc/drivers/MySQLDriverTest.java
src/test/java/ortus/boxlang/runtime/types/QueryTest.java
src/test/java/tools/JDBCTestUtils.java

The initial fix was for 
https://ortussolutions.atlassian.net/browse/BL-1186
But required some significant refactoring, which also overlapped heavily with these small fixes/additions.
https://ortussolutions.atlassian.net/browse/BL-1693
https://ortussolutions.atlassian.net/browse/BL-1699
https://ortussolutions.atlassian.net/browse/BL-1700
https://ortussolutions.atlassian.net/browse/BL-1701

BL-1186, BL-1693, BL-1699, BL-1700, BL-1701

---

src/main/java/ortus/boxlang/runtime/config/Configuration.java
src/main/java/ortus/boxlang/runtime/modules/ModuleRecord.java
src/main/java/ortus/boxlang/runtime/scopes/Key.java
src/main/java/ortus/boxlang/runtime/services/ModuleService.java
src/modules/test/src/main/bx/ModuleConfig.bx
src/test/java/ortus/boxlang/runtime/modules/ModuleRecordTest.java

this.mapping for modules needs to support simple string and a struct of mapping options
```
this.mapping = "mapping"
```
This creates the mapping and sets it to external = false
```
this.mapping = {
name : "mapping",
external : true
}
```
This creates the mapping and sets it to external = true

BL-1760 Extended Module Mappings

---

build.gradle
src/main/java/ortus/boxlang/runtime/components/net/HTTP.java
src/main/java/ortus/boxlang/runtime/net/HttpManager.java
src/test/java/ortus/boxlang/runtime/components/net/HTTPTest.java

Handles client certs in HTTP Requests
https://ortussolutions.atlassian.net/browse/BL-1808

BL-1808 Resolve - Add support for client certificate functionality
